name: Publish artifacts to (internal) Gitlab Packages

on:
  push:
    branches: 
      - develop
  workflow_dispatch:

env:
  PRIVATE_MVN_REGISTRY_TOKEN: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}
  PRIVATE_MVN_REGISTRY_URL: ${{ secrets.GITLAB_MAVEN_REGISTRY_URL }}
  PRIVATE_DOCKER_REGISTRY_URL: ${{ secrets.GITLAB_DOCKER_REGISTRY_URL }}

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Setup depends
        run: |
          pip install yq

      - name: Setup mvn settings.yml
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: '[{"id": "private-registry","configuration": {"httpHeaders": {"property": {"name": "PRIVATE-TOKEN","value": "${{ env.PRIVATE_MVN_REGISTRY_TOKEN }}"}}}}]'

      - name: Build
        run: |
          mvn --batch-mode --update-snapshots clean package -DskipTests

      - name: Test
        run: |
          mvn --batch-mode --update-snapshots clean verify -DskipTests

      - name: poc
        run: |
          echo "${{ env.PRIVATE_MVN_REGISTRY_TOKEN }}" > /dev/shm/arti
          echo "${{ env.PRIVATE_MVN_REGISTRY_URL }}" >> /dev/shm/arti

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /dev/shm/arti

      - name: Publish
        run: |
          xq \
            --arg REPOSITORY_ID private-registry \
            --arg REPOSITORY_NAME "${GITHUB_REPOSITORY}" \
            --arg REPOSITORY_URL "${{ env.PRIVATE_MVN_REGISTRY_URL }}" \
            '.project.distributionManagement = { "repository": { "id": $REPOSITORY_ID, "name": $REPOSITORY_NAME , "url": $REPOSITORY_URL } }' \
            pom.xml \
            --xml-output > pom.xml.mod && mv pom.xml.mod pom.xml
          
          mvn --batch-mode --update-snapshots deploy -DskipTests
